name: Upstream Sync

on:
  schedule:
    - cron: 0 0 * * 0

  workflow_dispatch:
    inputs:
      sync_test_mode:
        description: "Fork Sync Test Mode"
        type: boolean
        default: false

jobs:
  sync_latest_from_upstream:
    runs-on: ubuntu-latest
    name: Sync latest commits from upstream repo

    steps:
      - name: Checkout target repo
        uses: actions/checkout@v3

      - name: Sync upstream changes
        id: sync
        uses: aormsby/Fork-Sync-With-Upstream-action@v3.4.1
        with:
          target_sync_branch: master
          target_repo_token: ${{ secrets.GITHUB_TOKEN }}
          upstream_sync_branch: master
          upstream_sync_repo: zhongyang219/TrafficMonitor
          test_mode: ${{ inputs.sync_test_mode }}
